version: "2"
services:
    web:
        build: 
            context: .
            dockerfile: dockerfile
        volumes: 
            - '.:/app'
            - '/app/node_modules'
        ports:
            - "3000:3000"